project_id = "drrugowjfdfymamcaovd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
port = 54324

[edge_functions]
enabled = true
port = 54325

[functions.analyze-pdf]
verify_jwt = true

[functions.ai-tutor-chat]
verify_jwt = true

[functions.quiz-generator]
verify_jwt = true

[functions.save-quiz-attempt]
verify_jwt = true